### PR TITLE
Masonry layout

### PR DESCRIPTION
**Pull request by dan1elhughes**
image

image

image

image

### CODE REVIEW

**Comment by vickyhughes** [comment]
this looks like a phone layout on my laptop, any idea why?
image

**Comment by dan1elhughes** [comment]
Ah - because it was deployed before #19 was merged 😄 I'll rebase it

**Comment by vickyhughes** [comment]
it still looks the same, should it?? also the pictures are really low res but that might be because it's a test deployment? thank you 😌

**Comment by vickyhughes** [comment]
Actually the pictures on the main portfolio page look quite blurry on the live website too. Do you know why that might be?

**Pull request merged**
